ModuleDescriptor.json
which gets included in most of the other logical permission sets,
so the bit should be available where needed
=> Added "usergroups.collection.get" to "can view users"

pom.xml
* There are no groovy files in this project.
* The Groovy-Eclipse configurator for m2eclipse is not compatible with AspectJ used for RAMLs: https://github.com/groovy/groovy-eclipse/wiki/Groovy-Eclipse-Maven-plugin
=> Remove groovy-eclipse from pom.xml

descriptors/ModuleDescriptor-template.json
1. Fixed mismatch between raml file and ModuleDescriptor.
2. Added "configuration.entries.item.get" permission for "/bl-users/forgotten/password" and "/bl-users/forgotten/username" endpoints.
Jira link: [MODUSERBL-48](https://issues.folio.org/browse/MODUSERBL-48)
=> MODUSERBL-48: Fix module descriptor

ramls/servicepoint.json, src/test/java/org/folio/rest/jaxrs/model/ServicePointTest.java
*Purpose*
In order to stop new properties in service points from causing failures during login, additional properties could be temporarily allowed in the schema until there is a better approach.
*Limitations*
* There are a couple of simple unit tests to demonstrate this behaviour. They use the RAML Module Builder object mapper directly, which isn't ideal, if either the response class or the main code is changed these tests could provide false results. 
It might be possible to use the response class (and the convertToPojo method) but I didn't have time to investigate this due to the urgency of the change.
In future it could be preferable to extract the part of mod-users-bl which uses that and test that aspect instead, which would be more robust to implementation changes. 
*Other …
=> Temporarily allow additional properties in service points MODUSERBL-67 

src/main/java/org/folio/rest/impl/BLUsersAPI.java, src/test/java/org/folio/rest/HeadersForwardingTest.java
Reset password by link does not work after latest changes to mod-users-bl (security logging).
Reason: okapi headers (token, tenant, etc.) are not forwarded in requests to other modules.
[MODUSERBL-66](https://issues.folio.org/browse/MODUSERBL-66)
=> MODUSERBL-66 Reset password by link does not work

descriptors/ModuleDescriptor-template.json
Align the value with that used in folio-ansible for reference environments.
=> FOLIO-2003 Use containerMemory as for folio-ansible

descriptors/ModuleDescriptor-template.json, ramls/mod-users-bl.raml
Changes in the version of the mod-login https://github.com/folio-org/mod-login/pull/64 affect changes in the modules: 
-  'edge-oai-pmh',
-  'edge-orders',
-  'edge-patron',
-  'edge-rtac',
-  'ui-users',
-  'mod-users-bl'
-  'edge-sip2'
-  'mod-login'
=> Raising the interface version related to mod-login API breaking change

ramls/mod-users-bl.raml, ramls/updateCredentials.json
making metadata.createdByUserId optional
Make a copy https://github.com/folio-org/mod-login/blob/master/ramls/updateCredentials.json
as https://github.com/folio-org/raml/commit/b2209740e798e9b73e3dfa13f48e089c657ff4cc
removed the file from the raml-util submodule.
=> MODUSERBL-75: Update raml-util submodule

Dockerfile, descriptors/ModuleDescriptor-template.json
Use new Alpine base docker image with more recent Java 8 (222) with +UseContainerSupport, and JAVA_OPTIONS MaxRAMPercentage to manage container memory.
See notes at [FOLIO-2358](https://issues.folio.org/browse/FOLIO-2358).
=> MODUSERBL-82 FOLIO-2358 manage container memory

src/main/java/org/folio/service/PasswordResetLinkServiceImpl.java, src/test/java/org/folio/rest/GeneratePasswordRestLinkTest.java
Fixes [MODUSERBL-78](https://issues.folio.org/browse/MODUSERBL-78)
Currently, when we send reset password email to user, we have hard code `24 hours` in template.
-create logic for checking time in minutes/hours/days/weeks
-add two tokens to context
-change and add tests
=> [MODUSERBL-78] Implementing token support `link expiration time` in the template

ramls/userdata.json
PR addresses the issue from [MODUSERBL-89](https://issues.folio.org/browse/MODUSERBL-89) 
If there is a difference between User schemas from mod-users and mod-users-bl then allow all unknown properties to be added into `additionalProperties`. Those unknown properties are not need by mod-users-bl to do the work. So they can be ignored and saving them in `additionalProperties` is a way to do it.
This should resolve any further cases when a new property defined for User in mod-users cannot be processed by mod-user-bl without explicit definition. 
Below is an example of how `customFields` deserealized in mod-users-bl w/o the fields being present in the schema:
=> MODUSERBL-89 Allow additional properties in User

ramls/userdata.json
Resolves issue [MODUSERBL-101](https://issues.folio.org/browse/MODUSERBL-101)
Set `"additionalProperties": true` in `personal` object that should allow any additional properties received from mod-users
=> MODUSERBL-101 Fix not recognize field "preferredFirstName"

src/main/java/org/folio/rest/impl/BLUsersAPI.java, src/test/java/org/folio/rest/HeadersForwardingTest.java
This pull request resolves [MODUSERBL-95](https://issues.folio.org/browse/MODUSERBL-95)
The simple solution to this issue was to append a limit criteria to the query for service points. I investigated creating a test to show that more than 10 service points would be supplied, but since the data is retrieved from mod-inventory-storage, the test data for service points is mocked and testing the contents of mocked data seemed pointless. I would recommend a UI test to verify more than 10 service points can be displayed.
I was able to test these changes using the folio/testing vagrant and swapping out the modified module. I was able to confirm the fix was successful.
=> Added limit value to service point query

pom.xml
https://issues.folio.org/browse/MODUSERBL-109 - Logging is broken for the module
* Fix logging by adding a filter to maven shade plugin that removes log4j cache file.
* Add manifest entry to fix `WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.`
=> MODUSERBL-109: Fix logging.

src/main/java/org/folio/service/PasswordResetLinkServiceImpl.java
Send correct notification to mod-notify to have a valid date in the email notification.
* Add dateTime to notification context
=> MODTEMPENG-59 Update notification context to have dateTime

pom.xml
The JUnit4 test rule TemporaryFolder contains a local information disclosure
vulnerability: TemporaryFolder on unix-like systems does not limit access to created files.
https://github.com/advisories/GHSA-269g-pwp5-87pp
https://nvd.nist.gov/vuln/detail/CVE-2020-15250
Changing to version 4.13.1 fixes this.
=> JUnit 4.13.1 fixing TemporaryFolder vulnerability (CVE-2020-15250)

NEWS.md, pom.xml
My understanding from reading the wiki on this issue is
that if a module uses RMB and does not have an explicit
log4j dependency declared, upgrading the RMB to a 
version that has the log4j fix in should solve the issue.
This module fits that description, so I have moved
the RMB version to 33.0.4, the closest compatible 
version that contains the fix.
=> MODUSERBL-123: Log4j vulnerability verification and correction

NEWS.md, descriptors/ModuleDescriptor-template.json
I looked through the list of undefined permissions and checked in the modules that would/should
define them.  In all cases, it looked as thought he module was already using a permission
necessary to interact-the listed permissions look like they are malformed versions of valid
permissions-so I removed all of them entirely.  I didn't add anything to the news file, as this 
isn't the sort of change that would produce a visible effect, but I did start the entry for the 
next minor version.
=> MODUSERBL-140: Undefined permissions

descriptors/ModuleDescriptor-template.json
This was removed in login interface 7.0.
=> Remove reference to login.item.get MODUSERBL-141

src/main/java/org/folio/rest/impl/BLUsersAPI.java, src/main/java/org/folio/rest/impl/InitAPIs.java, src/main/java/org/folio/rest/util/HttpClientUtil.java, src/main/java/org/folio/service/password/UserPasswordService.java, src/main/java/org/folio/service/password/UserPasswordServiceImpl.java, src/test/java/org/folio/rest/util/HttpClientUtilTest.java
Reuse one HttpClient for all requests.
Note that `WebClient.wrap(client)` doesn't create a new client but reuses
the passed HttpClient.
=> MODUSERBL-80: Vert.x HttpClient objects are leaked

pom.xml, src/test/java/org/folio/rest/util/HttpClientUtilTest.java
https://issues.folio.org/browse/MODUSERBL-151
The `${vertx-version}` are removed because the IDE warns about them being unnecessary thanks to the dependencyManagement.
=> MODUSERBL-151 Upgrade to RMB 34.0.0.

.github/workflows/api-doc.yml, .github/workflows/api-lint.yml, .github/workflows/api-schema-lint.yml, Jenkinsfile, README.md, ramls/mod-users-bl.raml
[FOLIO-3678](https://issues.folio.org/browse/FOLIO-3678)
Use GitHub Workflows for [api-lint](https://dev.folio.org/guides/api-lint/) and [api-schema-lint](https://dev.folio.org/guides/describe-schema/) and [api-doc](https://dev.folio.org/guides/api-doc/)
(instead of Jenkins-operated CI stages).
=> FOLIO-3678 MODUSERBL-164 Use GitHub Workflows api-lint and api-schema-lint and api-doc

ramls/compositeUser.json, ramls/loginCredentials.json, src/main/java/org/folio/rest/impl/BLUsersAPI.java, src/test/java/org/folio/rest/BLUsersAPITest.java, src/test/java/org/folio/rest/GeneratePasswordRestLinkTest.java, src/test/java/org/folio/rest/HeadersForwardingTest.java, src/test/java/org/folio/rest/MockOkapi.java
We need to support changes made in mod-login to have succesfull login in consortia setup [MODLOGIN-205](https://issues.folio.org/browse/MODLOGIN-205). The login API retrieves the right tenant for the user, and we should use this tenant to call the user API.
_self endpoint is changed to support retrieving shadow user information after context (affiliation is switched). What does it mean? When affiliation is changed UI sends _self  request to refresh user data (permissions, service points etc), in `master branch` implementation _self relies on username in token to find user, but for cross-tenant usage username is different for all shadow users, as a result we need to use parameter that is the same for all users (main and shadow) across tenants which is uuid. Additionally we keep previous …
=> [MODUSERBL-166] - Using tenantId from login response

src/main/java/org/folio/rest/client/impl/AuthTokenClientImpl.java, src/main/java/org/folio/rest/exception/TokenNotFoundException.java, src/main/java/org/folio/rest/util/ExceptionHelper.java, src/test/java/org/folio/rest/GeneratePasswordRestLinkTest.java
The purpose of this PR is to add a 404 response for /auth/login and /token endpoints
Added 404 response in AuthTokenClientImpl class for /token endpoint and for /auth/login they are already handling 404 response.
=> MODUSERBL-180 Module needs to respond 404 when 404 is received from /authn/login and /token endpoints

descriptors/ModuleDescriptor-template.json
Purpose:
The purpose of the PR is to implement - https://folio-org.atlassian.net/browse/MODUSERBL-189 
Approach:
request-storage dependency with version 6.0 is added in Module descriptor of mod-users-bl .
=> MODUSERBL-189 Missing interface dependency in module descriptor

descriptors/ModuleDescriptor-template.json
The purpose of the PR is to fix MODUSERBL-213
Added the missed interface dependency reported in the jira.
=> MODUSERBL-213 Adding missed interface dependency in module descriptor
