- .editorconfig
- ModuleDescriptor.json
- docker/docker-entrypoint.sh
- pom.xml
- src/main/resources/mock_content.json
> FOLIO-351 tidy 1

- ModuleDescriptor.json
> Remove high-level permission sets defined in ui-users/package.json.

- Jenkinsfile
- NEWS.md
- src/main/java/org/folio/rest/impl/BlUsersAPI.java
> FOLIO-351 whitespace tidy 2

- descriptors/ModuleDescriptor-template.json
- pom.xml
- src/main/java/org/folio/rest/impl/BLUsersAPI.java
- src/test/java/org/folio/rest/MockOkapi.java
Triggering a rebuild of API docs
following configuration changes
[pull/239](https://github.com/folio-org/folio-org.github.io/pull/239)
Here only code-style whitespace changes.
> FOLIO-903 apidocs config

- .gitignore
- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
- ramls/identifier.json
- ramls/mod-users-bl.raml
- src/main/java/org/folio/rest/impl/BLUsersAPI.java
- src/test/java/org/folio/rest/BLUsersAPITest.java
- src/test/java/org/folio/rest/MockOkapi.java
- src/test/java/org/folio/rest/MockOkapiTest.java
- src/test/java/org/folio/rest/Query.java
Implementation for MODLOGIN stories
Assign the fields to locate Folio account when user forgets password
Assign the fields to locate a Forgotten username
> MODLOGIN-44-45

- descriptors/ModuleDescriptor-template.json
This is a fix for https://jenkins-aws.indexdata.com/job/folio-org/job/mod-users-bl/job/master/27
> MODLOGIN-44 MODLOGIN-45 fix configuration-client module dependency

- NEWS.md
- README.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
- ramls/mod-users-bl.raml
- src/main/java/org/folio/rest/impl/BLUsersAPI.java
- src/main/java/org/folio/rest/impl/InitAPIs.java
- src/main/java/org/folio/rest/util/OkapiConnectionParams.java
- src/main/java/org/folio/rest/util/RestUtil.java
- src/main/java/org/folio/services/UserPasswordService.java
- src/main/java/org/folio/services/UserPasswordServiceImpl.java
- src/main/java/org/folio/services/package-info.java
- src/test/java/org/folio/rest/BLUsersAPITest.java
- src/test/java/org/folio/rest/MockOkapi.java
- Added new endpoint POST /settings/myprofile/password to BlUsersResource component within mod-users-bl module.
- this endpoint use mod-password-validator to check a password and mod-login to store the password if it is validated successfully.
- grant permissions needed to call mod-login POST /authn/update to mod-users-bl
- API tests for new endpoint added
> MODLOGIN-53:add endpoint to change user password

- .gitmodules
- ramls/credentials.json
- ramls/mod-users-bl.raml
- ramls/permissionUser.json
- ramls/proxyfor.json
- ramls/servicepoint.json
- ramls/servicepointsexpandeduser.json
- ramls/servicepointsuser.json
- ramls/userdata.json
- ramls/usergroup.json
Following standard configuration.
Did 'git mv ramls/raml ramls/raml-util'
Adjusted paths in RAML and JSON.
> MODUSERBL-47 Move git submodule to ramls/raml-util

- descriptors/ModuleDescriptor-template.json
added missing dependencies to ModuleDescriptor
> Add missing dependencies

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
- ramls/mod-users-bl.raml
- ramls/passwordReset.json
- src/main/java/org/folio/rest/client/PasswordResetActionClient.java
- src/main/java/org/folio/rest/client/impl/PasswordResetActionClientImpl.java
- src/main/java/org/folio/rest/impl/BLUsersAPI.java
- src/main/java/org/folio/service/PasswordResetLinkService.java
- src/main/java/org/folio/service/PasswordResetLinkServiceImpl.java
- src/test/java/org/folio/rest/BLUsersAPITest.java
- src/test/java/org/folio/rest/GeneratePasswordRestLinkTest.java
- src/test/java/org/folio/rest/MockOkapi.java
Jira link: [MODUSERBL-52](https://issues.folio.org/browse/MODUSERBL-52)
> MODUSERBL-52: Implement endpoint for creating/resetting password by link

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
- ramls/mod-users-bl.raml
- ramls/passwordReset.json
- src/main/java/org/folio/rest/client/PasswordResetActionClient.java
- src/main/java/org/folio/rest/client/impl/PasswordResetActionClientImpl.java
- src/main/java/org/folio/rest/impl/BLUsersAPI.java
- src/main/java/org/folio/rest/util/ExceptionHelper.java
- src/main/java/org/folio/service/PasswordResetLinkService.java
- src/main/java/org/folio/service/PasswordResetLinkServiceImpl.java
- src/test/java/org/folio/rest/BLUsersAPITest.java
- src/test/java/org/folio/rest/GeneratePasswordRestLinkTest.java
- src/test/java/org/folio/rest/MockOkapi.java
MODUSERBL-53 Adding functionality of sending notification to /bl-users/forgotten/password and /bl-users/forgotten/username
This pull request is based on branch MODUSERBL-52 that is not merged to master yet.
To see changes use:  [Comparing changes MODUSERBL-52 MODUSERBL-53](https://github.com/folio-org/mod-users-bl/compare/MODUSERBL-52...MODUSERBL-53)
> MODUSERBL-53 Adding functionality of sending notification

- NEWS.md
- pom.xml
> Tmp release 4.3.1

- pom.xml
- src/main/java/org/folio/rest/impl/BLUsersAPI.java
Also, remove calling postgres-runner (not in use).
Do not copy raml-util to apidocs separately as it is already
a sub directory of raml.
> Upgrade to RMB 23.2.1, Vert.x 3.5.4

- src/main/java/org/folio/rest/impl/BLUsersAPI.java
- src/main/java/org/folio/service/PasswordResetLinkServiceImpl.java
- src/test/java/org/folio/rest/GeneratePasswordRestLinkTest.java
MODUSERBL-61 
Adding username to default search fields for forgot password endpoint
Resolves: [MODUSERBL-61](https://issues.folio.org/browse/MODUSERBL-61)
> MODUSERBL-61 Adding username to default search fields

- src/main/java/org/folio/rest/impl/BLUsersAPI.java
- src/main/java/org/folio/service/PasswordResetLinkServiceImpl.java
- src/main/java/org/folio/service/password/UserPasswordService.java
- src/main/java/org/folio/service/password/UserPasswordServiceImpl.java
- src/test/java/org/folio/rest/HeadersForwardingTest.java
**Purpose**
Update API contract to implement a user password reset by link
Resolves: [MODUSERBL-73](https://issues.folio.org/browse/MODUSERBL-73)
> MODUSERBL-73 Update API contract to implement a user password reset by link [Reset passwords: user can reset password by link]

- src/main/java/org/folio/rest/impl/BLUsersAPI.java
- src/test/java/org/folio/rest/HeadersForwardingTest.java
**Purpose**
Fix bug. Username with "_" or space is treated incorrectly
Resolve: [MODUSERBL-77](https://issues.folio.org/browse/MODUSERBL-77)
> MODUSERBL-77 Username with "_" or space is treated incorrectly

- src/main/java/org/folio/rest/impl/BLUsersAPI.java
**Purpose**
Fix bug. Username with "_" or space is treated incorrectly
Resolve: [MODUSERBL-77](https://issues.folio.org/browse/MODUSERBL-77)
> MODUSERBL-77 Apply URL encoding

- src/test/java/org/folio/rest/BLUsersAPITest.java
- src/test/java/org/folio/rest/MockOkapi.java
See also https://dev.folio.org/guides/uuids/
> Fix UUID version: 99999999-9999-4999-9999-999999999999

- pom.xml
- src/main/java/org/folio/rest/client/impl/PasswordResetActionClientImpl.java
- src/main/java/org/folio/rest/impl/BLUsersAPI.java
- src/main/java/org/folio/rest/util/OkapiConnectionParams.java
- src/main/java/org/folio/rest/util/RestUtil.java
- src/main/java/org/folio/service/PasswordResetLinkServiceImpl.java
- src/main/java/org/folio/service/password/UserPasswordServiceImpl.java
- src/test/java/org/folio/rest/GeneratePasswordRestLinkTest.java
- src/test/java/org/folio/rest/MockOkapi.java
- src/test/java/org/folio/rest/MockOkapiTest.java
- src/test/java/org/folio/rest/TestUtil.java
https://issues.folio.org/browse/MODUSERBL-90 - Upgrade to RAML Module Builder 30.0.0
> MODUSERBL-90: Upgrade to RMB v30.

- src/main/java/org/folio/rest/client/impl/NotificationClientImpl.java
- src/test/java/org/folio/rest/GeneratePasswordRestLinkTest.java
- remove throwing exception if notify response status is not 200;
- add log for the error;
- create test;
Resolves: [MODUSERBL-100](https://issues.folio.org/browse/MODUSERBL-100)
> MODUSERSBL-100 Add error log for notify response

- src/main/java/org/folio/service/PasswordResetLinkServiceImpl.java
- src/test/java/org/folio/rest/GeneratePasswordRestLinkTest.java
Add limit on password-reset link expiration
* set expiration time to 4 weeks when config value is more than 4 weeks
* update tests
> MODUSERBL-99 Add limit on password-reset link expiration

- src/main/java/org/folio/rest/impl/BLUsersAPI.java
- src/test/java/org/folio/rest/BLUsersAPITest.java
- src/test/java/org/folio/rest/MockOkapi.java
The spaces around OR need to be URL encoded as %20 when sent to /users API.
> MODUSERBL-114: Connection closed for CQL "username=devonte OR ..."

- NEWS.md
- pom.xml
- src/test/java/org/folio/rest/HeadersForwardingTest.java
The wire mock based tests for logging in were changed as they failed when after upgrading to RMB 33.0.0 (presumably due to the changes in URL encoding)
> Upgrade to RMB 33.0.0 MODUSERBL-119

- src/test/java/org/folio/rest/BLUsersAPITest.java
- src/test/java/org/folio/rest/GeneratePasswordRestLinkTest.java
- src/test/java/org/folio/rest/HTTPMockTest.java
- src/test/java/org/folio/rest/HeadersForwardingTest.java
- src/test/java/org/folio/rest/MockOkapiTest.java
- src/test/java/org/folio/rest/TestUtil.java
Wait until verticle deployment has finished before continuing the
test execution.
Otherwise the build fails on some computers with this error:
BLUsersAPITest.before:81->insertData:100 ? Connect Connection refused
> MODUSERBL-118: deployVerticle race condition: Connection refused

- descriptors/ModuleDescriptor-template.json
https://issues.folio.org/browse/MODUSERBL-121
> MODUSERBL-121 Update feesfines version to 17.0

- NEWS.md
- pom.xml
Resolves [MODUSERBL-137](https://issues.folio.org/browse/MODUSERBL-137)
> Upgraded RMB to 33.2.4

- pom.xml
- src/main/java/org/folio/rest/impl/BLUsersAPI.java
Update RMB from 33.2.4 to 33.2.9.
Update Vert.x from 4.1.4 to 4.2.7.
This indirectly fixes these security issues:
Update netty-codec from 4.1.67 to 4.1.74 fixing Denial of Service (DoS) https://nvd.nist.gov/vuln/detail/CVE-2021-37136 , https://nvd.nist.gov/vuln/detail/CVE-2021-37137 and HTTP Request Smuggling https://nvd.nist.gov/vuln/detail/CVE-2021-43797
Update jackson-databind from 2.11.4 to 2.13.2.1 fixing Denial of Service (DoS) https://nvd.nist.gov/vuln/detail/CVE-2020-36518 , https://security.snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-2326698
> MODUSERBL-145: Update dependencies (RMB, Vertx, Jackson, Netty)

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
* Increase max container mem to 512MB (MODUSERBL-144)
* Rebuild to fix ZipException on 64-bit systems (FOLIO-3484)
> Release 7.2.3

- src/main/java/org/folio/rest/impl/BLUsersAPI.java
Not pretty as socket is  never reused, but should avoid resource
leaks for now. Many code smells not fixed by this. Just keeping it
small.
> Add closeClient for all cases MODUSERBL-147

- Dockerfile
- Jenkinsfile
- pom.xml
_[MODUSERBL-172](https://issues.folio.org/browse/MODUSERBL-172) : Update to Java 17 mod-users-bl_
Update the module to Java 17 and identify issues.
https://wiki.folio.org/display/TC/JDK+17+and+Java+17
Changed the java sdk version to 17 wherever applicable
> MODUSERBL-172 : Update to Java 17 mod-users-bl

- descriptors/ModuleDescriptor-template.json
- src/main/java/org/folio/rest/impl/BLUsersAPI.java
- src/main/java/org/folio/service/PasswordResetLinkService.java
- src/main/java/org/folio/service/PasswordResetLinkServiceImpl.java
- src/main/java/org/folio/service/consortia/CrossTenantUserServiceImpl.java
[MODUSERBL-169](https://issues.folio.org/browse/MODUSERBL-169)
> [MODUSERBL-169] - Fix for forgot username/password

- README.md
- ramls/mod-users-bl.raml
- src/main/java/org/folio/rest/client/impl/AuthTokenClientImpl.java
- src/test/java/org/folio/rest/GeneratePasswordRestLinkTest.java
The purpose of this PR is to add a new end point /token/sign
Added new end point in AuthTokenClientImpl class
New endpoint(/token/sign) in AuthTokenClientImpl class is getting called.
> MODUSERBL-176 Needs to use new /token/sign endpoint of mod-at

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
> MODUSERBL-177 Poppy release

- descriptors/ModuleDescriptor-template.json
Resolves: [MODUSERBL-178](https://issues.folio.org/browse/MODUSERBL-178)
> [MODUSERBL-178] Raise feesfines interface versions to 19

- src/main/java/org/folio/rest/impl/BLUsersAPI.java
https://issues.folio.org/browse/MODUSERBL-170
Two if conditions lines cannot be covered with test, because servicepoints in spCollectionJson can never be null, it could be empty.
It is partially covered because null can never happen.
> Remove duplicated code

- pom.xml
- src/main/java/org/folio/rest/client/impl/AuthTokenClientImpl.java
- src/main/java/org/folio/rest/client/impl/CirculationStorageModuleClientImpl.java
- src/main/java/org/folio/rest/client/impl/ConfigurationClientImpl.java
- src/main/java/org/folio/rest/client/impl/FeesFinesModuleClientImpl.java
- src/main/java/org/folio/rest/client/impl/NotificationClientImpl.java
- src/main/java/org/folio/rest/client/impl/PasswordResetActionClientImpl.java
- src/main/java/org/folio/rest/client/impl/UserModuleClientImpl.java
- src/main/java/org/folio/rest/util/ExceptionHelper.java
- src/main/java/org/folio/service/consortia/CrossTenantUserServiceImpl.java
_Describe the purpose of the pull request._
To Upgrade raml and vertex version for Q release.
_How does this change fulfill the purpose?_
Ugraded the version as per https://github.com/folio-org/raml-module-builder/blob/master/doc/upgrading.md#version-352
_Describe the research stage. Add links to blog posts, patterns, libraries or addons used to solve this problem._
> MODUSERBL-187 - Update rmb and vertex version.

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
> Release 7.7.0

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
> MODUSERBL-192 - To release 7.7.1 

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
> MODUSERBL-192 - Release 7.7.1

- src/main/java/org/folio/rest/impl/BLUsersAPI.java
- src/test/java/org/folio/rest/BLUsersAPITest.java
To fix the issue mentioned in MODUSERBL-182 the token that is received and was decoded with Base64.decoder which was throwing the error java.lang.IllegalArgumentException: Illegal base64 character 5f. 
As a fix applied Base64.getUrlDecoder() and this decoded the token correctly and allowed the user login.
> MODUSERBL-182 - Users with non-ASCII characters in username are unable to login

- NEWS.md
- src/main/java/org/folio/rest/impl/BLUsersAPI.java
- src/main/resources/log4j.properties
- src/test/java/org/folio/rest/HeadersForwardingTest.java
https://folio-org.atlassian.net/browse/MODUSERBL-191
Cannot log in if a user doesn't have permissions in mod-permissions. 
- make perms/users call safe if there are no permissions
- update tests
- cover several NPE
> MODUSERBL-191: fix login error

- NEWS.md
- pom.xml
https://folio-org.atlassian.net/browse/MODUSERBL-197
> Relese 7.8.0

- descriptors/ModuleDescriptor-template.json
Moved request-storage dependency from required to optional.
> MODUSERBL-199 - Adding the dependency request-storage as optional.

- descriptors/ModuleDescriptor-template.json
Adding "notify.users.item.post" permission.
> MODUSERBL-205 - Adding "notify.users.item.post" permission.

- ramls/mod-users-bl.raml
- src/main/java/org/folio/rest/impl/BLUsersAPI.java
https://folio-org.atlassian.net/browse/MODUSERBL-200
> MODUSERBL-200: Removed unused include parameter

- pom.xml
> Upgrade version to 7.9.2-SNAPSHOT

- src/main/java/org/folio/rest/impl/BLUsersAPI.java
- src/test/java/org/folio/rest/BLUsersAPITest.java
https://folio-org.atlassian.net/browse/MODUSERBL-208
> MODUSERBL-208: Query with username fails when username contains non-url-encoded characters

- descriptors/ModuleDescriptor-template.json
https://folio-org.atlassian.net/browse/MODUSERBL-214
> MODUSERBL-214: added required permission for Delete request-preference, permissions, authen_credentails

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
- src/main/java/org/folio/rest/impl/BLUsersAPI.java
- src/test/java/org/folio/rest/BLUsersAPITest.java
https://folio-org.atlassian.net/browse/MODUSERBL-215
> Ramsons release 7.9.3

- NEWS.md
- pom.xml
- src/main/java/org/folio/rest/impl/BLUsersAPI.java
- src/test/java/org/folio/rest/BLUsersAPITest.java
Quesnelia (R1 2024) Service Patch 7 release 7.7.5
https://folio-org.atlassian.net/browse/MODUSERBL-216
> Quesnelia release 7.7.5

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
https://folio-org.atlassian.net/browse/MODUSERBL-219
> Sunflower release 7.10.0

- pom.xml
https://folio-org.atlassian.net/browse/MODUSERBL-221
> MODUSERBL-221: Upgraded POM libs version after Sunflower Releases

- src/main/java/org/folio/rest/exception/MultipleEntityException.java
- src/main/java/org/folio/rest/impl/BLUsersAPI.java
- src/main/java/org/folio/service/consortia/CrossTenantUserServiceImpl.java
- src/test/java/org/folio/rest/BLUsersAPITest.java
**Approach**
- Perform the check to see if the information provided (email/phone number/etc) is tied to multiple accounts.  If it is, we should log a message (WARN) with relevant details.
- We should NOT send an email when the info provided is tied to multiple accounts.
- We should NOT return an error indicating the success/failure of the operation.  This leads to a username enumeration vulnerability.
Story:
https://folio-org.atlassian.net/browse/MODUSERBL-225
> MODUSERSBL-225: Search users in all tenants when using "Forgot password" and "Forgot username" links

- NEWS.md
- pom.xml
- src/main/java/org/folio/rest/exception/MultipleEntityException.java
- src/main/java/org/folio/rest/impl/BLUsersAPI.java
- src/main/java/org/folio/service/consortia/CrossTenantUserServiceImpl.java
- src/test/java/org/folio/rest/BLUsersAPITest.java
- Release v7.10.2
- Preparation for the next development cycle
> Release v7.10.2

- NEWS.md
- README.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
- src/main/java/org/folio/rest/impl/BLUsersAPI.java
- src/main/java/org/folio/rest/util/FeatureFlags.java
- src/test/java/org/folio/rest/BLUsersAPITest.java
- src/test/java/org/folio/rest/HeadersForwardingEurekaTest.java
- src/test/java/org/folio/rest/HeadersForwardingTest.java
Call `mod-roles-keycloak` instead `mod-permissions` in POST /bl-users/login-with-expiry.
https://folio-org.atlassian.net/browse/MODUSERBL-224
> MODUSERBL-224: use mod-roles-keycloak for login expand perms
